# Schema for the configuration files of the Tooltip Textfield module.

tooltip_textfield.settings:
  type: config_object
  label: 'Tooltip Textfield settings'
  mapping:
    tooltip_textfield:
      type: textfield
      label: 'Text'

field.storage_settings.tooltip_textfield:
  type: mapping
  label: 'Tooltip Textfield settings'
  mapping:
    max_length:
      type: integer
      label: 'Maximum length'

field.field_settings.tooltip_textfield:
  type: mapping
  label: 'Tooltip Textfield settings'

field.value.tooltip_textfield:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: label
      label: 'Value'
    format:
      type: string
      label: 'Text format'

field.formatter.settings.tooltip_textfield:
  type: mapping
  label: 'Tooltip Textfield display format settings'

field.widget.settings.tooltip_textfield:
  type: mapping
  label: 'Tooltip Textfield display format settings'
  mapping:
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'
